# Generated by Django 5.0.2 on 2024-02-22 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('score', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='score',
            options={'ordering': ['-age']},
        ),
        migrations.AddField(
            model_name='score',
            name='age',
            field=models.PositiveSmallIntegerField(default=45),
            preserve_default=False,
        ),
    ]
